
server:
  port: 8080

spring:
  application:
    name: accounts
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled : true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
     - "qa"  # enter profile you want to activate

build:
  version: "1.0"

accounts:
  message: "Welcome to Account Related local API's"
  contactDetails:
    name: "Jay Pande - Developer"
    email: "jmaypande@gmail.com"
  support:
    - (+91) 7351733644


#springdoc:
#  swagger-ui:
#    path:
